# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/GitHub/26-Arch/vivado/lab5_project/lab5_project.cache/wt [current_project]
set_property parent.project_path G:/GitHub/26-Arch/vivado/lab5_project/lab5_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/GitHub/26-Arch/vivado/lab5_project/lab5_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  G:/GitHub/26-Arch/vsrc
  G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/clk_wiz_0
} [current_fileset]
add_files -quiet G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0.dcp
set_property used_in_implementation false [get_files G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0.dcp]
read_verilog G:/GitHub/26-Arch/vivado/src/device.svh
set_property file_type "Verilog Header" [get_files G:/GitHub/26-Arch/vivado/src/device.svh]
read_verilog -library xil_defaultlib -sv {
  G:/GitHub/26-Arch/vsrc/include/config.sv
  G:/GitHub/26-Arch/vsrc/include/common.sv
  G:/GitHub/26-Arch/vsrc/util/CBusArbiter.sv
  G:/GitHub/26-Arch/vsrc/util/DBusToCBus.sv
  G:/GitHub/26-Arch/vsrc/util/IBusToCBus.sv
  G:/GitHub/26-Arch/vsrc/VTop.sv
  G:/GitHub/26-Arch/vivado/src/with_delay/bram_wrapper.sv
  G:/GitHub/26-Arch/vivado/src/with_delay/cbus_crossbar.sv
  G:/GitHub/26-Arch/vsrc/src/core.sv
  G:/GitHub/26-Arch/vivado/src/device.sv
  G:/GitHub/26-Arch/vsrc/util/mmu.sv
  G:/GitHub/26-Arch/vsrc/mycpu_top.sv
  G:/GitHub/26-Arch/vivado/src/with_delay/soc_top.sv
  G:/GitHub/26-Arch/vivado/src/with_delay/basys3_top.sv
}
read_verilog -library xil_defaultlib {
  G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0_stub.v
  G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_stub.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/GitHub/26-Arch/vivado/src/Basys-3-Master.xdc
set_property used_in_implementation false [get_files G:/GitHub/26-Arch/vivado/src/Basys-3-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top basys3_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef basys3_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file basys3_top_utilization_synth.rpt -pb basys3_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
