# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: G:/GitHub/26-Arch/vivado/src/Basys-3-Master.xdc

# IP: G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
