// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VSimTopFPGA.h for the primary calling header

#ifndef VERILATED_VSIMTOPFPGA___024ROOT_H_
#define VERILATED_VSIMTOPFPGA___024ROOT_H_  // guard

#include "verilated.h"


class VSimTopFPGA__Syms;

class alignas(VL_CACHE_LINE_BYTES) VSimTopFPGA___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_perfInfo_clean,0,0);
        VL_IN8(io_perfInfo_dump,0,0);
        VL_OUT8(io_uart_out_valid,0,0);
        VL_OUT8(io_uart_out_ch,7,0);
        VL_OUT8(io_uart_in_valid,0,0);
        VL_IN8(io_uart_in_ch,7,0);
        CData/*0:0*/ SimTopFPGA__DOT__ram_valid;
        CData/*0:0*/ SimTopFPGA__DOT__ram_ready;
        CData/*0:0*/ SimTopFPGA__DOT__ram_last;
        CData/*0:0*/ SimTopFPGA__DOT__device_valid;
        CData/*0:0*/ SimTopFPGA__DOT__device_ready;
        CData/*0:0*/ SimTopFPGA__DOT__dbg_cpu_tx_write;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__flush_mmu;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__fault_is_insn;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT____Vcellinp__dcvt__reset;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_pending;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_buf_valid;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_req_new_fire;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_resp_fire;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_pop_buf;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_resp_to_id;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_resp_to_buf;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_redirect_pending;
        CData/*1:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_redirect_bubble;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_drop_resp_pending;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_valid;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_trap;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_wen;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_word;
        CData/*3:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_alu_cmd;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_load;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_store;
        CData/*2:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_mem_size;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_mem_unsigned;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_branch;
        CData/*2:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_br_funct3;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_jal;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_jalr;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_wb_pc4;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_csr_wen;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_ecall;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_mret;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_sret;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_amo;
        CData/*4:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_amo_cmd;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_illegal;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_ebreak;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_is_sfence;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_misalign;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_instr_misalign;
        CData/*1:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__privilege_mode;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__halted;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__trap_commit;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mmu_trap;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__trap_redirect;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mret_redirect;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mdu_req;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_to_mem_blocks_front;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__stall_ex_busy;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__stall_mem_busy;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__raw_hazard_ex;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__raw_hazard_mem;
    };
    struct {
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_flush_front;
        CData/*7:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mem_store_strobe;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mdu_core_out_valid;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__amo_issue;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__amo_issued_q;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__amo_done_q;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT____VdfgRegularize_h47660625_0_12;
        CData/*4:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_decode__DOT__id_rd;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_busy;
        CData/*3:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_cmd;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_is_word;
        CData/*6:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_steps_left;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_div_signed;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_div_is_rem;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_q_neg;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_r_neg;
        CData/*6:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__width_steps;
        CData/*5:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__sign_bit;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__op1_neg;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__op2_neg;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_is_pow2;
        CData/*5:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_pow2_shift;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_is_signed;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_is_rem;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_ecall;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_mret;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_sret;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_illegal;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_ebreak;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_misalign_data;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__wb_misalign_instr;
        CData/*2:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__state;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__translate_en;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_is_insn;
        CData/*7:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_wstrb;
        CData/*2:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_size;
        CData/*1:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_level;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__trap_pending;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__req_addr_bit2;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__req_inflight;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__issue_now;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__inst__DOT__okay;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__inst__DOT__req_inflight;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__inst__DOT__resp_seen;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__inst__DOT__issue_now;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__icvt__DOT__inst__DOT__resp_fire;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__dcvt__DOT__okay;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__dcvt__DOT__req_inflight;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__dcvt__DOT__resp_seen;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__dcvt__DOT__issue_now;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__dcvt__DOT__resp_fire;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT__any_valid;
        CData/*0:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT__lock_valid;
        CData/*0:0*/ SimTopFPGA__DOT__u_bram__DOT__txn_active;
        CData/*7:0*/ SimTopFPGA__DOT__u_bram__DOT__latched_wstrobe;
        CData/*0:0*/ SimTopFPGA__DOT__u_bram__DOT__is_write;
        CData/*0:0*/ SimTopFPGA__DOT__u_bram__DOT__real_valid;
        CData/*0:0*/ SimTopFPGA__DOT__u_bram__DOT__ready_read;
        CData/*0:0*/ SimTopFPGA__DOT__u_bram__DOT__last_read;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__txn_fire;
        CData/*7:0*/ SimTopFPGA__DOT__u_device__DOT__tx_write_byte;
        CData/*7:0*/ SimTopFPGA__DOT__u_device__DOT__uart_lcr;
        CData/*7:0*/ SimTopFPGA__DOT__u_device__DOT__uart_ier;
        CData/*3:0*/ SimTopFPGA__DOT__u_device__DOT__switch;
    };
    struct {
        CData/*4:0*/ SimTopFPGA__DOT__u_device__DOT__console_rx_wptr;
        CData/*4:0*/ SimTopFPGA__DOT__u_device__DOT__console_rx_rptr;
        CData/*5:0*/ SimTopFPGA__DOT__u_device__DOT__console_rx_count;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__console_rx_empty;
        CData/*1:0*/ SimTopFPGA__DOT__u_device__DOT__txState;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__bitDone;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__tx_start;
        CData/*7:0*/ SimTopFPGA__DOT__u_device__DOT__fifo_count;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__fifo_full;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__dbg_ever_uart_write_reg;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__dbg_ever_device_read_reg;
        CData/*3:0*/ SimTopFPGA__DOT__u_device__DOT__rxBitIndex;
        CData/*1:0*/ SimTopFPGA__DOT__u_device__DOT__rxState;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__rxBitSync;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__rxBit;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__rxByteReady;
        CData/*7:0*/ SimTopFPGA__DOT__u_device__DOT__rxByte;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__disk_rdy;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT__txn_done_pulse;
        CData/*0:0*/ SimTopFPGA__DOT__u_device__DOT____Vlvbound_h99cc83ff__0;
        CData/*7:0*/ SimTopFPGA__DOT__u_device__DOT____Vlvbound_h24e30222__0;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__delegate_to_s__14__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__16__mode;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__18__mode;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__20__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__delegate_to_s__21__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__23__mode;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__25__mode;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__27__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__active;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__hit;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__allow;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__a_mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__active;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__hit;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__allow;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__a_mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__active;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__hit;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__allow;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__a_mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__active;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__hit;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__allow;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__a_mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__active;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__hit;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__allow;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__a_mode;
    };
    struct {
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__mode;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__active;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__hit;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__allow;
        CData/*0:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__Vfuncout;
        CData/*1:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__a_mode;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_decode__DOT__id_csr_addr;
        SData/*8:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__vpn1;
        SData/*8:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__vpn0;
        SData/*15:0*/ SimTopFPGA__DOT__u_bram__DOT__counter;
        SData/*15:0*/ SimTopFPGA__DOT__u_device__DOT__mtime_div;
        SData/*13:0*/ SimTopFPGA__DOT__u_device__DOT__bitTmr;
        SData/*9:0*/ SimTopFPGA__DOT__u_device__DOT__rxShiftReg;
        SData/*13:0*/ SimTopFPGA__DOT__u_device__DOT__rxBitTmr;
        SData/*11:0*/ __Vfunc_sanitize_csr_write__1__addr;
        IData/*31:0*/ SimTopFPGA__DOT__dbg_cycle_count;
        IData/*31:0*/ SimTopFPGA__DOT__dbg_device_access_count;
        IData/*31:0*/ SimTopFPGA__DOT__dbg_ram_access_count;
        IData/*31:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_buf_instr;
        IData/*31:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__dbg_trap_count;
        IData/*31:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__dbg_commit_count;
        VlWide<3>/*64:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_div_rem;
        VlWide<3>/*64:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_rem_next;
        VlWide<5>/*150:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT____Vxrand_hee1f0c2a__0;
        IData/*31:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT__select;
        IData/*31:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT__lock_select;
        IData/*17:0*/ SimTopFPGA__DOT__u_bram__DOT__unnamedblk1__DOT__waddr;
        IData/*31:0*/ SimTopFPGA__DOT__u_device__DOT____Vxrand_h8df4b479__0;
        IData/*31:0*/ SimTopFPGA__DOT__u_device__DOT__bitIndex;
        IData/*31:0*/ SimTopFPGA__DOT__u_device__DOT__disk_blockno;
        IData/*31:0*/ SimTopFPGA__DOT__u_device__DOT__gen_dbg_live__DOT__dbg_live_count;
        IData/*31:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__ones;
        IData/*31:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__ones;
        IData/*31:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__ones;
        IData/*31:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__ones;
        IData/*31:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__ones;
        IData/*31:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__ones;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(io_logCtrl_log_begin,63,0);
        VL_IN64(io_logCtrl_log_end,63,0);
        VL_IN64(io_logCtrl_log_level,63,0);
        VlWide<5>/*150:0*/ SimTopFPGA__DOT__oreq;
        VlWide<3>/*65:0*/ SimTopFPGA__DOT__oresp;
        QData/*63:0*/ SimTopFPGA__DOT__device_rdata;
        VlWide<3>/*64:0*/ SimTopFPGA__DOT__u_vtop__DOT__ireq_core;
        QData/*33:0*/ SimTopFPGA__DOT__u_vtop__DOT__iresp_core;
        VlWide<5>/*139:0*/ SimTopFPGA__DOT__u_vtop__DOT__dreq_core;
        VlWide<3>/*64:0*/ SimTopFPGA__DOT__u_vtop__DOT__ireq_bus;
        VlWide<5>/*139:0*/ SimTopFPGA__DOT__u_vtop__DOT__dreq_bus;
        VlWide<3>/*65:0*/ SimTopFPGA__DOT__u_vtop__DOT__dresp_bus;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__fault_vaddr;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__fault_cause;
        VlWide<4>/*96:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_r;
        VlWide<15>/*468:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_r;
        VlWide<13>/*400:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mem_r;
        VlWide<13>/*400:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__wb_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_pc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_req_pc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_buf_pc;
    };
    struct {
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fetch_redirect_pc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_op1;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_op2;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_imm;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__id_dec_csr_wdata;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mstatus;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mtvec;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mie;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mscratch;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mcause;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mtval;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_mepc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__csr_satp;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__cycle_cnt;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__fault_pc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__trap_redirect_pc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mem_stage_result;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_result;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_mem_addr;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__ex_redirect_pc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mem_store_data_shifted;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__mdu_core_out_result;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_decode__DOT__id_rs2_val;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_mul_acc;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_mul_a;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_mul_b;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_div_quot;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mdu_div_divisor;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__width_mask;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__op1_eff;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__op2_eff;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__dividend_abs;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__divisor_abs;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mul_acc_next;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mul_a_next;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mul_b_next;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_quot_next;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__q_unsigned;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__r_unsigned;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__final_val;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mul_src0;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__mul_src1;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_q_abs_fast;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_r_abs_fast;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_mdu__DOT__div_pow2_mask;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_mip_raw;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_stvec_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_sscratch_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_sepc_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_scause_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_stval_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_medeleg_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_mideleg_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_mcounteren_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_menvcfg_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_pmpcfg0_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__csr_pmpaddr0_r;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_vaddr;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_wdata;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pte_addr;
        QData/*63:0*/ SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__saved_pte;
        VlWide<5>/*150:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT__selected_req;
        VlWide<5>/*150:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT__lock_req;
        VlWide<3>/*65:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT____Vlvbound_hfd226540__0;
    };
    struct {
        VlWide<3>/*65:0*/ SimTopFPGA__DOT__u_vtop__DOT__mux__DOT____Vlvbound_h10130eb1__0;
        QData/*63:0*/ SimTopFPGA__DOT__u_bram__DOT__latched_addr;
        QData/*63:0*/ SimTopFPGA__DOT__u_bram__DOT__latched_wdata;
        QData/*63:0*/ SimTopFPGA__DOT__u_bram__DOT__bram_rdata;
        QData/*63:0*/ SimTopFPGA__DOT__u_bram__DOT__unnamedblk1__DOT__wmask;
        QData/*63:0*/ SimTopFPGA__DOT__u_device__DOT__mtime;
        QData/*63:0*/ __Vfunc_sanitize_csr_write__1__Vfuncout;
        QData/*63:0*/ __Vfunc_sanitize_csr_write__1__data;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__delegate_to_s__14__cause;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_excp_cause__15__Vfuncout;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__16__Vfuncout;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__delegate_to_s__21__cause;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_excp_cause__22__Vfuncout;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__core__DOT__u_commit__DOT__u_csr__DOT__get_ecall_cause__23__Vfuncout;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__30__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__base;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__31__top;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__32__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__base;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__33__top;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__34__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__base;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__35__top;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__36__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__base;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__37__top;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__38__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__base;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__39__top;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_req_fault__40__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__addr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__cfg;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__paddr;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__base;
        QData/*63:0*/ __Vfunc_SimTopFPGA__DOT__u_vtop__DOT__u_mmu__DOT__pmp_entry_match__41__top;
        VlUnpacked<QData/*63:0*/, 32> SimTopFPGA__DOT__u_vtop__DOT__core__DOT__gpr;
        VlUnpacked<QData/*63:0*/, 262144> SimTopFPGA__DOT__u_bram__DOT__mem;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 16> SimTopFPGA__DOT__u_device__DOT__console_rx_fifo;
        VlUnpacked<IData/*31:0*/, 256000> SimTopFPGA__DOT__u_device__DOT__sim_disk_mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VSimTopFPGA__Syms* const vlSymsp;

    // CONSTRUCTORS
    VSimTopFPGA___024root(VSimTopFPGA__Syms* symsp, const char* v__name);
    ~VSimTopFPGA___024root();
    VL_UNCOPYABLE(VSimTopFPGA___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
