# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0.xci
# IP: The module: 'bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0.xci
# IP: The module: 'bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/GitHub/26-Arch/vivado/test-cpu/project/project_3/project_3.srcs/sources_1/ip/bram_0/bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
